### ISSUE TITLE
Add .gitignore for VS files.

### ISSUE THREAD

**Issue by MC01DA** [iLinked1337/Anarchy#1]

**Comment by iLinked1337** [comment]
do you mean the .vs files?

**Comment by iLinked1337** [comment]
because i don't think those are even getting uploaded

**Comment by MC01DA** [comment]
It's still good to have. It's not only for .vs files. For other usefull other things too.

You have still the folders like bin and obj, what are not needed.
And that packages folder is also not needed since you have packages.config file., so when you open project in vs, it will ask to restore specific packages from nuget.

One simple .gitignore file and all that, done.

**Comment by iLinked1337** [comment]
fair enough. i'm new to git and haven't used it a lot, but when i figure out how gitignore works i'll do it :)
