### ISSUE TITLE
Bots Dont work

### ISSUE THREAD

**Issue by MentallyGone1** [iLinked1337/Anarchy#13]
` static void Main(string[] args)
        {
            DiscordSocketClient client = new DiscordSocketClient();
            client.Token = "Bot TokenHere";
            client.SendMessage(channelIDHere, "Test im online");
            Thread.Sleep(-1);
        }`
Throws off an Error i attempted to  do the same thing with a normal client but it also doesnt work

**Comment by Juxstin** [comment]
Discord changed shit wait for him to update

**Comment by ohkriss** [comment]
You are supposed to do client.Login("Bot TokenHere");

**Comment by iLinked1337** [comment]
1. You're supposed to use .Login() on socket clients. If you do not require Gateway functionality, just use a DiscordClient instead.
2. Prefixing your token with 'Bot ' allows you to log into bot accounts.
