### ISSUE TITLE
No mutual friends option

### ISSUE THREAD

**Issue by KibbeWater** [iLinked1337/Anarchy#16]
When going on GetProfile() theres MutualGuilds but not MutualFriends

**Comment by Juxstin** [comment]
https://github.com/iLinked1337/Anarchy/blob/master/Anarchy/REST/User/Settings/FriendSourceFlags.cs#L37

I think it does. If you fully can't get it working ill take a look and do a PR.

**Comment by iLinked1337** [comment]
The GetProfile endpoint does not return mutual friends.
