### ISSUE TITLE
I have a problem wich my code

### ISSUE THREAD

**Issue by MAGIIKZZGAMING** [iLinked1337/Anarchy#17]
hello ilinked i have a problem : 

`            string accounts = File.ReadAllLines("tokens.txt").ToString();

            client.Token = accounts;`

**Comment by KibbeWater** [comment]
Ok I'll help you a bit.

- First, your computer is not a fucking mind reader, please give a valid path to the tokens file. If you want to get a file from the same directory as where the executable got executed you can read more [here](https://stackoverflow.com/questions/1658518/getting-the-absolute-path-of-the-executable-using-c)

- Second, You are trying to use an array as a token, to login to each token you would need a new client or if it's just a simple task like logging in and changing the status you could make a foreach statement to execute it for every client.

- Third, I guess you want to login to the client, To do so you need to have a DiscordSocketClient and use the DiscordSocketClient.Login(string token) function to login and not DiscordSocketClient.Token

Please for the love of god try to learn the coding language before even trying to ask anyone questions cause were not here to teach you how to code. You need to learn that by yourself

**Comment by iLinked1337** [comment]
This should've been posted on StackOverflow as it's not about a bug with Anarchy, but i'll help you anyway. File.ReadAllLines returns a string[] (so every line is an element in that), ToString() makes no sense here. 

So to solve your issue, replace it with
```c
 string[] accounts = File.ReadAllLines("tokens.txt");

client.Token = accounts[0]; // this would get the first line from the file.
```
