### ISSUE TITLE
Guild Duplicator broken?

### ISSUE THREAD

**Issue by SkidPolice** [iLinked1337/Anarchy#18]
![image](https://user-images.githubusercontent.com/60057999/72676586-aff22000-3a8a-11ea-8ee6-034cd2804a10.png)

**Comment by KibbeWater** [comment]
Make your own, theres probably some old code thats not supported. Stop skidding

**Comment by Juxstin** [comment]
@uwudev use the dev branch https://github.com/iLinked1337/Anarchy/tree/dev

**Comment by Iskra-12** [comment]
@KibbeWater this shows you re a skid lmao this was an issue inside of anarchy its self as of "bad request" IDK if you re stupid or just retarded

**Comment by KibbeWater** [comment]
> @KibbeWater this shows you re a skid lmao this was an issue inside of anarchy its self as of "bad request" IDK if you re stupid or just retarded

That code worked perfectly for me before. If it's not working now then it's probably cause of discord api updates. I don't fucking understand what your problem is

**Comment by Moooog** [comment]
another place you're being retarded. stop posting here thanks (to Kibbe)

> stop skidding
also kibbe
> the code worked perfectly for me before

**Comment by iLinked1337** [comment]
This issue is caused by an update Discord recently put in place. Upgrading to the latest Anarchy version should work.
