### ISSUE TITLE
MessageProperties() not working

### ISSUE THREAD

**Issue by IDONKNOWSHIT** [iLinked1337/Anarchy#19]
So it says

'Access to "MessageProperties" is not possible due to the degree of protection.

and i dont know what to do

**Comment by KibbeWater** [comment]
you can use like a public variable in a private method pretty sure.

**Comment by IDONKNOWSHIT** [comment]
and Message.Author.Id is not there?

**Comment by KibbeWater** [comment]
You need to use Message.Author.User.Id

**Comment by IDONKNOWSHIT** [comment]
thx

**Comment by IDONKNOWSHIT** [comment]
MessageProperties() the class is intern can i change it?

**Comment by IDONKNOWSHIT** [comment]
or how would i send a message cause im very confused i tried everything and nothing works

**Comment by KibbeWater** [comment]
You don't need to change message properties. I'm not gonna make your code neither is anyone else, please learn c# and come back when you are done. I'm not gonna help you more than that theres samples in the github repo

**Comment by IDONKNOWSHIT** [comment]
ok ill close the case  its just broken and poorly described.WHAT MUST I DO TO SEND MESSAGES.
and i can do c# i develop games

**Comment by KibbeWater** [comment]
bud, the source code is in your face, you should look at it. also following a brackeys tutorial doesn't make you a c# god, more like a skid
