### ISSUE TITLE
GetGuildMembers is returning Missing Access

### ISSUE THREAD

**Issue by Slimig** [iLinked1337/Anarchy#25]
https://discordapp.com/developers/docs/resources/guild#list-guild-members
Seems to be broken rn. I tested it and i got "Discord.DiscordHttpException: 50001 Missing Access". Also I had to verify my Discord account with email again. Pls fix :)

**Comment by iLinked1337** [comment]
I had the exact same issue today, and also had to re-verify my email. If i had to make a guess i'd say Discord changed their API, so i'll have a look.

**Comment by iLinked1337** [comment]
As far as i can see this is an issue with Discord's own API, so i guess you'll have to use a socket client for now :(
