### ISSUE TITLE
Discord.DiscordHttpException: 50013 Missing Permissions on StartCall

### ISSUE THREAD

**Issue by Iskra-12** [iLinked1337/Anarchy#27]
client.StartCall(CHANNEL ID);
yes I changed channel id to a dm channel id
Accounts are both friends with the account I'm trying to call and in a mutual guild

**Comment by iLinked1337** [comment]
`StartCall` should not be called when guilds are involved. Instead you should use `JoinVoiceChannel` (only available for DiscordSocketClient).

**Comment by Iskra-12** [comment]
I was using a DM Channel ID
