### ISSUE TITLE
Log in with multiple Tokens [Extended]

### ISSUE THREAD

**Issue by TheBackdoor** [iLinked1337/Anarchy#30]
How to login with Multiple Tokens?

i dont want to make more **DiscordSocketClients**.

i want something like that:
`Client.Login(myArray);`
or
```

foreach(string s in {my token array})
{
          Client.Login(s);
}
```

_to make maybe a raid system?.._

**Comment by KibbeWater** [comment]
just make a list and create a new DiscordClient for every iteration of the foreach loop

**Comment by iLinked1337** [comment]
Every client is supposed to be for **1** account (or token). so you should create multiple clients. furthermore, if you're writing a raidbot i'd highly suggest using DiscordClients instead.

**Comment by KibbeWater** [comment]
heres a short example
`var tokens = whatever list / array;
var clients = new List<DiscordClient>();

for(int i = 0; i < tokens.Count; i++){
var client = new DiscordClient();
client.Login(token[i]);
clients.Add(client);
}
`

I just wrote it without IDE so it probably needs tweaking but I believe you can do that yourself
