### ISSUE TITLE
difference between DiscordSocketClient and DiscordClient?

### ISSUE THREAD

**Issue by TheBackdoor** [iLinked1337/Anarchy#31]
what is the difference?

**Comment by KibbeWater** [comment]
first off stop opening tickets for everything. I'm 99% sure that DiscordSocketClient supports receiving messages and etc while DiscordClient is more optimized for larger use of more clients which I think only can do like joining servers and send messages but can't read whats being sent

**Comment by iLinked1337** [comment]
I agree with @KibbeWater. There's no need to create an issue about something like this.
It has already been explained in the readme.
