### ISSUE TITLE
send messages in Server dont work

### ISSUE THREAD

**Issue by TheBackdoor** [iLinked1337/Anarchy#32]
![d](https://user-images.githubusercontent.com/61780641/77302782-25c87100-6cf2-11ea-8620-5246afffb40c.PNG)

what is the error? just copied the code in the README.MD to test it.

**Comment by KibbeWater** [comment]
This is the last time I'm gonna provide support for you, stop opening issues for the last time. Use DiscordSocketClient and use client.GetChannel(channelId); and not guildId

**Comment by TheBackdoor** [comment]
Im opening issues cuz i need help. lol. i want to learn

**Comment by TheBackdoor** [comment]
@KibbeWater 
![d](https://user-images.githubusercontent.com/61780641/77312612-9a0b1080-6d02-11ea-8feb-f5079e923692.PNG)

**Comment by KibbeWater** [comment]
> @KibbeWater
> ![d](https://user-images.githubusercontent.com/61780641/77312612-9a0b1080-6d02-11ea-8feb-f5079e923692.PNG)

You gotta understand that to use this you need previous C# knowledge, you can't just jump into it thinking you can do it first try. after this me and probably nobody else will provide support. you also need to understand the basics of Discord and that 3333 is not a valid channel id.

The solution is to just replace TextChannel with var instead. Now stop opening tickets and close this one

**Comment by TheBackdoor** [comment]
@KibbeWater _i will close this ticket now_ **but** i want to say: Im not a beginner in c#. i maked many c# projects and a minimal obfuscator.
and if I want something to try, i will try cuz i want to learn and become a good dev.

...i needed to put something in the .GetChannel(); cuz if I put nothing in it, it will show a other error.
and i was too lazy to put the channel Id in it...

**you can also be nicer!**

_sry if I write anything wrong! im not good in english ^^_

**Comment by KibbeWater** [comment]
You have opened 3 tickets previously needing help explaining simple C#
Remember you are making a **ISSUE** not a help ticket in some discord server

**Comment by iLinked1337** [comment]
@TheBackdoor is getting pretty annoying

**Comment by iLinked1337** [comment]
Oh and also to clear up the issue, i'm behind on my documentation. To get a TextChannel you're supposed to do GetChannel().ToTextChannel().

**Comment by KibbeWater** [comment]
> Oh and also to clear up the issue, i'm behind on my documentation. To get a TextChannel you're supposed to do GetChannel().ToTextChannel().

even so it's not really needed unless you are trying to send a message in each channel of a guild cause you could just use client.SendMessage() which is way simpler than getting the channel first
