### ISSUE TITLE
Editing any code in the program seems to open up a rift in my bootyhole

### ISSUE THREAD

**Issue by manofmanytalents** [iLinked1337/Anarchy#4]
These rifts in my bootyhole are catastrophically big and I don't know how to fix them.

**Comment by manofmanytalents** [comment]
oh yea also give discord link yeaaaaaa

**Comment by KadePcGames** [comment]
this issue was solved in the latest release.
https://discord.gg/D5T3WY6

**Comment by manofmanytalents** [comment]
did discord get deleted btw
