### ISSUE TITLE
getAllGuildMembers() fails

### ISSUE THREAD

**Issue by TheFlyingPlatypus** [iLinked1337/Anarchy#9]
here is my code.
causes a freeze.
`

        private static void Client_OnMessageReceived(DiscordSocketClient client, MessageEventArgs args)
        {
            if (args.Message.Author.User.Id == client.User.Id)
            {
                switch (args.Message.Content.Split(' ')[0])
                {
                    case "!t":
                        Console.WriteLine("started");
                        Console.WriteLine(client.GetAllGuildMembers((ulong)args.Message.GuildId)[0]);
                         break;
                }
            }
        }
    }
}
`

please fix, Thanks!

**Comment by JenzV** [comment]
this is not an issue.

**Comment by TheFlyingPlatypus** [comment]
> this is not an issue.

the method does not work at all
how is this not an issue?

**Comment by Moooog** [comment]
its not an isue because you're doing it wrong. use it in foreach

**Comment by TheFlyingPlatypus** [comment]
> its not an isue because you're doing it wrong. use it in foreach

do you mean like this? because i get the same result
   ```
      foreach(GuildMember g in client.GetAllGuildMembers((ulong)args.Message.GuildId))
                        {
                            Console.WriteLine(g.Nickname);
                        }
```

**Comment by iLinked1337** [comment]
the reason it freezes is that you're blocking the gateway with your code that requires other stuff to come through the gateway. running the code in a Task.Run() will do the trick just fine

**Comment by oSumAtrIX** [comment]
I have implemented @iLinked1337 comment https://github.com/iLinked1337/Anarchy/issues/9#issuecomment-562821790
```cs
_client.Login(token);
_client.OnLoggedIn += (s, e) => {
 Task.Run(() => {
  foreach(var guildMember in _client.GetAllGuildMembers(_serverid)) {
   Console.WriteLine(guildMember.Nickname);
  }
 });
};
```
But as @TheFlyingPlatypus says, the code freezes or rather `GetAllGuildMembers()` does not return a List of GuildMember objects
